### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by kqmaverick** [gitgiggety/plugin.video.stash#8] opened 2023-02-24 01:26 UTC
Just tried to set this up on a Kodi 20 install. I have tried Android and Windows and get the same error
[kodi.log](https://github.com/gitgiggety/plugin.video.stash/files/10819823/kodi.log)

**Comment by gitgiggety** [comment] 2023-02-26 19:20
Based on the log it looks like a duplicate of #7 and thus fixed in 0.0.7 (just released).

**Closed by gitgiggety** 2023-02-26 19:20 UTC
